### ISSUE TITLE
Use Cloud Service instead of Raspberry Pi

### ISSUE THREAD

**Issue by amitness** [requestsigdel/Earthquake-Notifier#1]
Really cool project.

You can use cloud service like Google App Engine to run the script endpoint every 5 minutes instead of setting up your own server in Raspberry Pi. This can remove the hardware dependency of your project.

Google App Engine provides free quota and that is more than enough for this use case. You can run it 24 / 7.

**Comment by requestsigdel** [comment]
Thank you. I will check Google App Engine soon. I do have a AWS account which I might use instead. Thank you for the feedback.
